version: 2
updates:
  # Enable version updates for npm/yarn/pnpm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    schedule:
      # `daily` = checks the npm registry for updates every weekday
      interval: 'daily'
    groups:
      prisma:
        patterns:
          - 'prisma'
          - '@prisma/client'
      next:
        patterns:
          - 'next'
          - 'eslint-config-next'
      aws-sdk:
        patterns:
          - '@aws-sdk/client-s3'
          - '@aws-sdk/s3-request-presigner'
